### ISSUE TITLE
Map generation fails if virtual boundary lines created

### ISSUE THREAD

**Issue by jeyrb** [DeebotUniverse/client.py#130]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Map generation fails if a virtual boundary line has been set rather than a box ( seems the API describes a line as a box with one side zero length )

### On which deebot vacuum you have the issue?

Deebot t8 AIVI

### Which version of the deebot-client are you using?

1.4.1

### Country

uk

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
Log Details (ERROR)


 
This error originated from a custom integration.
Logger: aiohttp.server
Source: custom_components/deebot/camera.py:53 
Integration: Deebot 4 Home Assistant (documentation, issues) 
First occurred: 09:29:51 (72 occurrences) 
Last logged: 09:43:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 741, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 759, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 179, in _async_get_image
    if image_bytes := await camera.async_camera_image(
  File "/config/custom_components/deebot/camera.py", line 53, in async_camera_image
    return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
  File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 312, in get_base64_map
    _draw_subset(subset, draw, image_box)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 126, in _draw_subset
    draw.dashed_line(points, dash=(3, 2), fill=_COLORS[subset.type], width=1)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/map.py", line 490, in dashed_line
    start = position / length
ZeroDivisionError: float division by zero
```

### Additional information

works fine with virtual boundary boxes.
Using via HACS on HASS, all at current versions as of 19th June 2022

**Comment by edenhaus** [comment]
Close due inactivity
