### ISSUE TITLE
Seems T50 Pro use zstd instead of 7z as the compression algorithm of map message

### ISSUE THREAD

**Issue by mzr1996** [DeebotUniverse/client.py#595]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

```
日志记录器: deebot_client.message
来源: /usr/local/lib/python3.12/site-packages/deebot_client/message.py:196
首次出现: 2024年11月13日 15:28:30 (8 次总计出现)
上次记录: 2024年11月13日 15:28:30

    ...
    Could not parse getMapSubSet: {..., 'compress': 1, 'value': 'KLUv/SB//QEAMgQKDKClbQC+WNsvI/5vYPMSO6jz8h7OwN2BYlTHRR2DYgSeurlRRyp2UAgALXwANbAWWqAuACQBKiDgFiUJ'}

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/deebot_client/message.py", line 190, in __handle_body_data
    response = cls._handle_body_data(event_bus, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/deebot_client/message.py", line 233, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/deebot_client/commands/json/map.py", line 278, in _handle_body_data_dict
    coordinates = decompress_7z_base64_data(data["value"]).decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/deebot_client/util/__init__.py", line 41, in decompress_7z_base64_data
    return dec.decompress(final_array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
_lzma.LZMAError: Input format not supported by decoder
```

I checked the `data['value']` and find it should be zstd format instead of 7z format, which means we need to use `zstd` instead of `lzma` package to decompress it.

### On which deebot device (vacuum) you have the issue?

Deebot T50 Pro

### Which version of the deebot-client are you using?

8.4.0

### Country

china

### Continent

unkown

**Comment by edenhaus** [comment]
Can you open a PR to add a option for it? Please also extend the capabilities for it, so we can set zstd for the T50

**Comment by lexiangmeng** [comment]
I have the same model T50 Pro as yours.
I have installed the integration and login to the Ecovas account, but nothing happened. It cannot detect any device. 
The log shows "Device class "0gxgac" not recognized". 
May I know which device id you are using?

**Comment by lexiangmeng** [comment]
It seems that it still doesn't work. Here is the log:
For model/class, I chose "4vhygi"

日志记录器: deebot_client.command
来源: runner.py:154
首次出现: 14:16:50 (8 次总计出现)
上次记录: 14:16:56

Could not parse getMapSet: {'ret': 'ok', 'resp': {'body': {'code': 20003, 'msg': 'rcp not support'}, 'header': {'fwVer': '1.79.0', 'hwVer': '0.1.1', 'pri': 1, 'ts': '1739773013568', 'tzm': 480, 'ver': '0.0.1', 'wkVer': '0.1.54'}}, 'id': 'VstP', 'payloadType': 'j'}
Could not parse getMapSet: {'ret': 'ok', 'resp': {'body': {'code': 20003, 'msg': 'rcp not support'}, 'header': {'fwVer': '1.79.0', 'hwVer': '0.1.1', 'pri': 1, 'ts': '1739773013713', 'tzm': 480, 'ver': '0.0.1', 'wkVer': '0.1.54'}}, 'id': 'U0ZH', 'payloadType': 'j'}
Could not parse getMapSet: {'ret': 'ok', 'resp': {'body': {'code': 20003, 'msg': 'rcp not support'}, 'header': {'fwVer': '1.79.0', 'hwVer': '0.1.1', 'pri': 1, 'ts': '1739773015876', 'tzm': 480, 'ver': '0.0.1', 'wkVer': '0.1.54'}}, 'id': 'GieA', 'payloadType': 'j'}
Could not parse getMapSet: {'ret': 'ok', 'resp': {'body': {'code': 20003, 'msg': 'rcp not support'}, 'header': {'fwVer': '1.79.0', 'hwVer': '0.1.1', 'pri': 1, 'ts': '1739773016100', 'tzm': 480, 'ver': '0.0.1', 'wkVer': '0.1.54'}}, 'id': 'VAnx', 'payloadType': 'j'}
Could not parse getMapSet: {'ret': 'ok', 'resp': {'body': {'code': 20003, 'msg': 'rcp not support'}, 'header': {'fwVer': '1.79.0', 'hwVer': '0.1.1', 'pri': 1, 'ts': '1739773016316', 'tzm': 480, 'ver': '0.0.1', 'wkVer': '0.1.54'}}, 'id': 'KRVs', 'payloadType': 'j'}

Thanks!
