### ISSUE TITLE
[deebot_client.commands.json.common] Command "clean" was not successfully. body={'code': 20003, 'msg': 'rcp not support'}

### ISSUE THREAD

**Issue by Shewinlong** [DeebotUniverse/client.py#710]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

[deebot_client.commands.json.common] Command "clean" was not successfully. body={'code': 20003, 'msg': 'rcp not support'}

### On which deebot device (vacuum) you have the issue?

DEEBOT X5 PRO ULTRA AI (lcbn6t)

### Which version of the deebot-client are you using?

9.4.0

### Country

hangzhou

### Continent

zh

### Anything in the logs that might be useful for us?

```txt
When I press start, ha report an error.     2024-12-21 11:57:24 2024-12-21 11:57:24.034 WARNING (MainThread) [deebot_client.commands.json.common] Command "clean" was not successfully. body={'code': 20003, 'msg': 'rcp not support'}
```

### Additional information

[config_entry-ecovacs-01JFKDYWRR5Y3FB9130MXAK04W (1).json](https://github.com/user-attachments/files/18217130/config_entry-ecovacs-01JFKDYWRR5Y3FB9130MXAK04W.1.json)

**Comment by edenhaus** [comment]
Your model is currently not supported so not sure how you even get so far.
Did you manually add your model?

**Comment by Shewinlong** [comment]
How to add  model

**Comment by Shewinlong** [comment]
> Your model is currently not supported so not sure how you even get so far. Did you manually add your model?
How to add model

**Comment by Shewinlong** [comment]
2024-12-26 17:36:50.975 WARNING (MainThread) [deebot_client.message] Could not parse getCleanInfo: {'code': 20003, 'msg': 'rcp not support'}
2024-12-26 17:36:50 Traceback (most recent call last):
2024-12-26 17:36:50   File "/usr/local/lib/python3.12/site-packages/deebot_client/message.py", line 63, in wrapper
2024-12-26 17:36:50     if response.state == HandlingState.ANALYSE:
2024-12-26 17:36:50        ^^^^^^^^^^^^^^
2024-12-26 17:36:50 AttributeError: 'NoneType' object has no attribute 'state'

**Comment by Shewinlong** [comment]
[home-assistant_ecovacs_2024-12-26T09-44-07.760Z.log](https://github.com/user-attachments/files/18251805/home-assistant_ecovacs_2024-12-26T09-44-07.760Z.log)

**Comment by jimmybonesde** [comment]
hi.

i got a x5 also and im reciving the same error in home assistant after pressing play on the vac

Logger: deebot_client.commands.json.common
Quelle: components/ecovacs/vacuum.py:346
Erstmals aufgetreten: 17:15:53 (2 Vorkommnisse)
Zuletzt protokolliert: 17:15:59
Command "clean" was not successfully. body={'code': 20003, 'msg': 'rcp not support'}


all other sensors are working good
only the start command is not supported.

Logger: deebot_client.message
Quelle: /usr/local/lib/python3.13/site-packages/deebot_client/message.py:72
Erstmals aufgetreten: 17:15:18 (7 Vorkommnisse)
Zuletzt protokolliert: 17:21:19

    Could not parse getCleanInfo: {'code': 20003, 'msg': 'rcp not support'}
    Could not parse getCleanPreference: {'code': 20005, 'msg': 'call setting service empty'}

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/deebot_client/message.py", line 65, in wrapper
    if response.state == HandlingState.ANALYSE:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'


pause, play, stop and locate ar not working
back to dock is working and all other sensors also.

here some pics:

![1](https://github.com/user-attachments/assets/e2dd8634-68e2-4566-bf21-fc6427205b5a)
![2](https://github.com/user-attachments/assets/b6c19350-1bc8-46dd-979b-91f76bd30c61)
![3](https://github.com/user-attachments/assets/02b8e559-6a7e-4e52-bb9f-784b823738df)
![4](https://github.com/user-attachments/assets/a7af5393-4a3e-40cf-990f-6610026b2d07)


a workaround is this for example room 6

start stop is working like this
maybe someone can help

The attached code files fix stop, start and pause for the X2 Omni. Tested with my X2.
Not sure best way to add clean a specific room.
As a workaround the following will clean room number 6 for example:

service: vacuum.send_command
target:
  entity_id: vacuum.wischroboter
data:
  command: clean_V2
  params:
    act: start
    content:
      type: freeClean
      value: 1,6
